import Navigation from "@/components/atoms/Navigation";
import Clocks from "@/components/organisms/Clocks";

import ClockContextProvider, {
  ClockContext,
} from "@/context/ClockContextProvider";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bloj</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <main>
        <Navigation />
        <ClockContextProvider>
          <Clocks />
        </ClockContextProvider>
      </main>
    </>
  );
}
