import Navigation from "@/components/atoms/Navigation";
import Blog from "@/components/organisms/Blog";
import Head from "next/head";

const tiposDeRelojes = () => {
  return (
    <>
      <Head>
        <title>Tipo de Relojes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <div className="bodyAnalogico">
        <Navigation />
        <Blog />
      </div>
    </>
  );
};

export default tiposDeRelojes;
